# Generated by Django 5.2.8 on 2025-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='diet_type',
            field=models.IntegerField(choices=[(1, 'Veg'), (2, 'Non-Veg'), (3, 'Vegan')], default=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='diet_type',
            field=models.IntegerField(choices=[(1, 'Veg'), (2, 'Non-Veg'), (3, 'Vegan')], default=1),
        ),
    ]
